/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.BanDAO;
import dao.MonDAO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.Ban;
import pojo.MyComboBox;

/**
 *
 * @author Dang Hoang Minh
 */
public class ChonBan extends javax.swing.JFrame {
    DefaultTableModel dtm2;
     ArrayList<String> dsBanDuocChon;
     ArrayList<Ban> dsBan;
    /**
     * Creates new form ChonBan
     */
    
   
    public ChonBan() {
        initComponents();
        this.setSize(800, 600);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(ChonBan.DISPOSE_ON_CLOSE); 
       
      
        dsBanDuocChon = new ArrayList<>(); // Khởi tạo danh sách
        dtm2 = new javax.swing.table.DefaultTableModel();   
       // hienThiDuLieuBan();
       khoiTaoBangTam();
       hienThiCSDLComboBoxBan();
    }
     public void khoiTaoBangTam()
    {
        
        String[] columnNamesBangTam = { "ID Bàn","Tên Bàn", "Số chỗ ngồi"};
        dtm2=new DefaultTableModel(columnNamesBangTam,0);
        tbBangTamBan.setModel(dtm2);
        
    }
   
    public void hienThiCSDLComboBoxBan()
    {
        
        ArrayList<Ban> dsBan = BanDAO.layDanhSachBan();
        DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel();

        for (Ban ban : dsBan) {
            
            MyComboBox cbb= new MyComboBox(ban.getBanID(), ban.getTenBan());
            
            comboBoxModel.addElement(cbb);
            
        }

       cbbBanTrong.setModel(comboBoxModel);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpChonBan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbbBanTrong = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbBangTamBan = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnThemBanVaoBangTam = new javax.swing.JButton();
        btnThucThiGopBan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Chọn bàn để gộp:");

        cbbBanTrong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tbBangTamBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbBangTamBan);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Màn hình chức năng gộp bàn");

        btnThemBanVaoBangTam.setText("Thêm");
        btnThemBanVaoBangTam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemBanVaoBangTamActionPerformed(evt);
            }
        });

        btnThucThiGopBan.setText("Thực thi");
        btnThucThiGopBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThucThiGopBanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpChonBanLayout = new javax.swing.GroupLayout(jpChonBan);
        jpChonBan.setLayout(jpChonBanLayout);
        jpChonBanLayout.setHorizontalGroup(
            jpChonBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpChonBanLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbBanTrong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnThemBanVaoBangTam)
                .addGap(210, 210, 210))
            .addGroup(jpChonBanLayout.createSequentialGroup()
                .addGroup(jpChonBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpChonBanLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel2))
                    .addGroup(jpChonBanLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(btnThucThiGopBan)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
        );
        jpChonBanLayout.setVerticalGroup(
            jpChonBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpChonBanLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpChonBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbbBanTrong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemBanVaoBangTam))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnThucThiGopBan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpChonBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jpChonBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosed
    private boolean kiemTraBan(int BanID)
    {
        boolean kq =false;
         for (int i = 0; i < dtm2.getRowCount(); i++) {
             // Duyệt qua mỗi cột trên dòng hiện tại

                 // Lấy giá trị tại dòng i, cột j
                 int banID = Integer.parseInt(dtm2.getValueAt(i, 0).toString());
                 
                 if(banID==BanID)
                 {
                     kq=true;
                     break;
                 }
        }
        
        
        return kq;
    }
    private void btnThemBanVaoBangTamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemBanVaoBangTamActionPerformed
        // TODO add your handling code here:
        
        dsBanDuocChon.clear();
        
        MyComboBox cbbBan=(MyComboBox)cbbBanTrong.getSelectedItem();
        int id=cbbBan.getMaLoai();
        String banID = String.valueOf(id);
        String tenBan=cbbBan.getTenLoai();
        String soChoNgoi= String.valueOf(BanDAO.laySoChoNgoi(id));
        if(kiemTraBan(id))
        {
            JOptionPane.showMessageDialog(this, "Bạn đã thêm bàn này !");
        }
        else{
            Object[] rowData = new Object[] {banID,tenBan,soChoNgoi};
            dtm2.addRow(rowData);

        
        
        }
         for (int i = 0; i < dtm2.getRowCount(); i++) {
            int ban_id = Integer.parseInt(dtm2.getValueAt(i, 0).toString());
            String ban_id_toString = String.valueOf(ban_id);
            dsBanDuocChon.add(ban_id_toString);
        }
       
         
         
         
        
        
//        
//        
//        txtTongTien.setText(String.valueOf(tongGia));
//        
//        
//        txtMaDH.setText(String.valueOf(DatHangDAO.layMaDHLonNhat()+1));


    }//GEN-LAST:event_btnThemBanVaoBangTamActionPerformed

    private void btnThucThiGopBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThucThiGopBanActionPerformed
        // TODO add your handling code here:
        dsBan=BanDAO.layDanhSachBan();
        // Thực hiện logic gộp bàn tại đây
        if (dsBanDuocChon.size() < 2) {
            JOptionPane.showMessageDialog(null, "Chọn ít nhất 2 bàn để gộp!");
            return;
        }
        
        // Xử lý logic gộp bàn, ví dụ: tạo một bàn mới với số ghế là tổng số ghế của các bàn được chọn
        int tongSoGhe = 0;
        for (String banID : dsBanDuocChon) {
            for (Ban ban : dsBan) {
                String ban_id=String.valueOf(ban.getBanID());
                if (ban_id.equals(banID)) {
                    tongSoGhe += ban.getSoGhe();
                    // Xóa bàn đã được chọn từ danh sách (hoặc bạn có thể đánh dấu là đã gộp)
                    BanDAO.capNhaTrangThaiBanGop(ban.getBanID());
                    break;
                }
            }
        }
        
        // Giả lập tạo bàn mới
        
        int ban_id_lon_nhat=BanDAO.layMaMonLonNhat()+1;
        Ban banMoi = new Ban(ban_id_lon_nhat,"Bàn "+String.valueOf(ban_id_lon_nhat),"Có khách",tongSoGhe);
        
        // Thêm bàn mới vào danh sách
        BanDAO.themBan(banMoi);
        
        // Làm mới giao diện để hiển thị bàn vừa gộp
        
        dsBanDuocChon.clear();
        JOptionPane.showMessageDialog(null, "Đã gộp bàn thành công!");
        
        
        
        
    
    }//GEN-LAST:event_btnThucThiGopBanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChonBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChonBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChonBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChonBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChonBan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThemBanVaoBangTam;
    private javax.swing.JButton btnThucThiGopBan;
    private javax.swing.JComboBox<String> cbbBanTrong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpChonBan;
    private javax.swing.JTable tbBangTamBan;
    // End of variables declaration//GEN-END:variables
}
