/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.BanDAO;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.Ban;
import pojo.MyComboBox;

/**
 *
 * @author Dang Hoang Minh
 */
public class TachBan extends javax.swing.JFrame {
    DefaultTableModel dtm2;
    ArrayList<Ban> dsBan;
    /**
     * Creates new form TachBan
     */
    ArrayList<Integer> dsSoGheSauTach;
    public TachBan() {
        initComponents();
        this.setSize(800, 600);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(ChonBan.DISPOSE_ON_CLOSE); 
        hienThiCSDLComboBoxBan();
        dsSoGheSauTach=new ArrayList<>();
        dtm2=new DefaultTableModel();
        hienThiCBBBan();
        khoiTaoBangTam();
    }
    
     public void hienThiCSDLComboBoxBan()
    {
        
        ArrayList<Ban> dsBan = BanDAO.layDanhSachBan();
        DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel();

        for (Ban ban : dsBan) {
            
            MyComboBox cbb= new MyComboBox(ban.getBanID(), ban.getTenBan());
            
            comboBoxModel.addElement(cbb);
            
        }

       cbbBanTrong.setModel(comboBoxModel);
    }
    private boolean kiemTraSoBanKhiTach()
    {
        boolean kq=true;
        int sb=Integer.parseInt(txtSLBan.getText());
        
        if(sb<=1)
            kq=false;
        
        return kq;
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbbBanTrong = new javax.swing.JComboBox<>();
        txtSLBan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSoGheNgoi = new javax.swing.JTextField();
        btnThucThiTachBan = new javax.swing.JButton();
        btnXacNhan = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtSoGheTruocKhiTach = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbBangTamBan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Màn hình tách bàn");

        jLabel2.setText("Chọn bàn muốn tách:");

        cbbBanTrong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbBanTrong.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbBanTrongItemStateChanged(evt);
            }
        });

        jLabel3.setText("Số lượng bàn muốn tách");

        jLabel4.setText("Số ghế ngồi bàn sau khi tách:");

        btnThucThiTachBan.setText("Thực thi");
        btnThucThiTachBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThucThiTachBanActionPerformed(evt);
            }
        });

        btnXacNhan.setText("xác nhận số ghế");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        jLabel5.setText("Số ghế trước khi tách");

        txtSoGheTruocKhiTach.setEnabled(false);

        tbBangTamBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbBangTamBan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 124, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtSoGheNgoi))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel3))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtSoGheTruocKhiTach)
                                            .addComponent(cbbBanTrong, 0, 89, Short.MAX_VALUE)
                                            .addComponent(txtSLBan))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnXacNhan)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnThucThiTachBan)
                .addGap(259, 259, 259))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbbBanTrong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSoGheTruocKhiTach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSLBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSoGheNgoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXacNhan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnThucThiTachBan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void hienThiSoGheDaChonDeTach()
    {
        String hienThiSgSauTach="Số ghế lần lượt: ";
        for (int sg: dsSoGheSauTach)
        {
            hienThiSgSauTach+=String.valueOf(sg)+" , ";
        }
       // lbHienThiSoGheSauKhiTach.setText(hienThiSgSauTach);
    }
     public void khoiTaoBangTam()
    {
        
        String[] columnNamesBangTam = { "Tên Bàn", "Số chỗ ngồi"};
        dtm2=new DefaultTableModel(columnNamesBangTam,0);
        tbBangTamBan.setModel(dtm2);
        
    } 
      private boolean kiemTraBan(int BanID)
    {
        boolean kq =false;
         for (int i = 0; i < dtm2.getRowCount(); i++) {
             // Duyệt qua mỗi cột trên dòng hiện tại

                 // Lấy giá trị tại dòng i, cột j
                 int banID = Integer.parseInt(dtm2.getValueAt(i, 0).toString());
                 
                 if(banID==BanID)
                 {
                     kq=true;
                     break;
                 }
        }
        
        
        return kq;
    }
    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        // TODO add your handling code here:
        int sg=Integer.parseInt(txtSoGheNgoi.getText());
        int sb=Integer.parseInt(txtSLBan.getText());
       
        if(dsSoGheSauTach.size()>=sb)
        {
            JOptionPane.showMessageDialog(this, "Bạn đã nhập đủ số lần chọn ghế để tách bàn");
        }
        
        
        
         
       int soDongTrongBang=tbBangTamBan.getRowCount();
        MyComboBox cbbBan=(MyComboBox)cbbBanTrong.getSelectedItem();
        int id=cbbBan.getMaLoai();
       int soGheTruocKhiTach=Integer.parseInt(txtSoGheTruocKhiTach.getText());
       
        int tongSoGheTrongDSSoGheTach=0;
        for(int soghe: dsSoGheSauTach)
            tongSoGheTrongDSSoGheTach+=soghe;
        if(tongSoGheTrongDSSoGheTach<soGheTruocKhiTach)
        {
            Object[] rowData = new Object[] {"Bàn tạm "+String.valueOf(soDongTrongBang),sg};
            dtm2.addRow(rowData);




            dsSoGheSauTach.clear();
             for (int i = 0; i < dtm2.getRowCount(); i++) {
                int so_ghe= Integer.parseInt(dtm2.getValueAt(i, 1).toString());

                dsSoGheSauTach.add(so_ghe);
            }
        }
        else
            JOptionPane.showMessageDialog(this, "Tổng số ghế sau tách không vượt quá số ghế trước khi tách");
         
    }//GEN-LAST:event_btnXacNhanActionPerformed
    private void hienThiCBBBan()
    {
        MyComboBox cbbDuocChon=(MyComboBox)cbbBanTrong.getSelectedItem();
        
        int banID=cbbDuocChon.getMaLoai();
       
        int soGhe = BanDAO.laySoChoNgoi(banID);
        txtSoGheTruocKhiTach.setText(String.valueOf(soGhe));
    }
    private void cbbBanTrongItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbBanTrongItemStateChanged
        // TODO add your handling code here:
        
       
        
        hienThiCBBBan();
        
        
        
    }//GEN-LAST:event_cbbBanTrongItemStateChanged

    private void btnThucThiTachBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThucThiTachBanActionPerformed
        // TODO add your handling code here:
          // TODO add your handling code here:
        dsBan=BanDAO.layDanhSachBan();
        // Thực hiện logic gộp bàn tại đây
        if (dsSoGheSauTach.size() < 2) {
            JOptionPane.showMessageDialog(null, "Chọn ít nhất 2 bàn để gộp!");
            return;
        }
        
        // Xử lý logic gộp bàn, ví dụ: tạo một bàn mới với số ghế là tổng số ghế của các bàn được chọn
        
        
            for (int soghe : dsSoGheSauTach) {
                int ban_id_lon_nhat=BanDAO.layMaMonLonNhat()+1;
                Ban banMoi = new Ban(ban_id_lon_nhat,"Bàn "+String.valueOf(ban_id_lon_nhat),"Còn trống",soghe);
        
                BanDAO.themBan(banMoi);
            }
        int soDongTrongBang=tbBangTamBan.getRowCount();
        MyComboBox cbbBan=(MyComboBox)cbbBanTrong.getSelectedItem();
        int id=cbbBan.getMaLoai();
       
        BanDAO.capNhaTrangThaiBanTach(id);
        // Giả lập tạo bàn mới
        
        
        // Thêm bàn mới vào danh sách
       
        
        // Làm mới giao diện để hiển thị bàn vừa gộp
        
        dsSoGheSauTach.clear();
        JOptionPane.showMessageDialog(null, "Đã tách bàn thành công!");
        
    }//GEN-LAST:event_btnThucThiTachBanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TachBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TachBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TachBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TachBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TachBan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThucThiTachBan;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JComboBox<String> cbbBanTrong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbBangTamBan;
    private javax.swing.JTextField txtSLBan;
    private javax.swing.JTextField txtSoGheNgoi;
    private javax.swing.JTextField txtSoGheTruocKhiTach;
    // End of variables declaration//GEN-END:variables
}
